name: aad
channels:
  - conda-forge
  - pytorch 
  - nvidia
  - fastai
dependencies:
  - python=3.7
  - matplotlib
  - numpy
  - numba
  - opencv
  - jupyterlab
  - ipywidgets
  - pytorch=1.9.0
  - torchvision=0.10.0
  - fastai=2.5.0
  - albumentations
  - tqdm
  - pip
  - pip:
    - fastseg==0.1.2
    - pyclothoids
    - pygame
    - imageio
    - imageio-ffmpeg
